### ISSUE TITLE
Missing @SideOnly on the onTooltipRender method and crash on some Server

### ISSUE THREAD

**Issue by Timicasto** [Tslat/AoA-InfoBundle#12]
Many Hybrid servers that are currently being used have eliminated redundant content, and some users will just stuff all Mods into the server without thinking.

However, these servers such as CatServer have already deleted net.minecraft.client.util.ITooltipFlag, so I suggest adding @SideOnly(Side.CLIENT) to this method to prevent this from happening.

**Comment by Tslat** [comment]
I don't actually know what you're asking
That only gets called on the client anyway?

If you have a crash, provide the crash report

**Comment by Timicasto** [comment]
It's also called on the server and caused a crash, The crash report only told me the class "net/minecraft/client/util/ITooltipFlag" was not found



`net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from More AoA Info (aoainfo)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
    at java.lang.Class.getConstructor0(Unknown Source)
    at java.lang.Class.getConstructor(Unknown Source)
    at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:130)
    at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:114)
    at net.tslat.aoainfo.AoAInfoBundle.fmlPreInit(AoAInfoBundle.java:13)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:636)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:336)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:166)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:593)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.util.ITooltipFlag
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 42 more
Caused by: java.lang.NullPointerException`

**Comment by Tslat** [comment]
Ah I see the issue, however InfoBundle is a client-only mod.. you shouldn't even have it installed on a dedicated server

**Comment by Timicasto** [comment]
Yeah I know, But this crash report was provided by a friend of mine, and from here I also realized that many people may not know that it can go wrong when loaded into the server, and that most client-side mods don't crash when loaded into the server, they just don't work

Anyway, I'm glad you noticed the problem.
